'use client'
import { useState, useEffect } from 'react'
import { SettingsSection } from './SettingsSection'
import { SettingRow } from './SettingRow'
import { SegmentedControl } from './SegmentedControl'
import { SettingsToggle } from './SettingsToggle'
import { SaveBar } from './SaveBar'
import type { WorkspaceSettings, SaveState, ScenarioVisibility, SlugStyle } from '@/lib/settings/types'

interface Props {
  data: WorkspaceSettings
  onSave: (patch: Partial<WorkspaceSettings>) => Promise<void>
}

export function PublishingSection({ data, onSave }: Props) {
  const [visibility, setVisibility] = useState<ScenarioVisibility>(data.publishingDefaultVisibility)
  const [requireValidation, setRequireValidation] = useState(data.publishingRequireValidation)
  const [searchIndexing, setSearchIndexing] = useState(data.publishingAllowSearchIndexing)
  const [slugStyle, setSlugStyle] = useState<SlugStyle>(data.publishingSlugStyle)
  const [saveState, setSaveState] = useState<SaveState>('idle')

  const isDirty =
    visibility !== data.publishingDefaultVisibility ||
    requireValidation !== data.publishingRequireValidation ||
    searchIndexing !== data.publishingAllowSearchIndexing ||
    slugStyle !== data.publishingSlugStyle

  useEffect(() => {
    if (isDirty && saveState === 'idle') setSaveState('dirty')
    if (!isDirty && saveState === 'dirty') setSaveState('idle')
  }, [isDirty])

  async function handleSave() {
    setSaveState('saving')
    try {
      await onSave({
        publishingDefaultVisibility: visibility,
        publishingRequireValidation: requireValidation,
        publishingAllowSearchIndexing: searchIndexing,
        publishingSlugStyle: slugStyle,
      })
      setSaveState('saved')
      setTimeout(() => setSaveState('idle'), 2000)
    } catch {
      setSaveState('error')
    }
  }

  function handleReset() {
    setVisibility(data.publishingDefaultVisibility)
    setRequireValidation(data.publishingRequireValidation)
    setSearchIndexing(data.publishingAllowSearchIndexing)
    setSlugStyle(data.publishingSlugStyle)
    setSaveState('idle')
  }

  return (
    <>
      <SettingsSection sectionKey="publishing" title="Publishing & Sharing" subtitle="Default settings for published scenarios.">
        <SettingRow label="Default visibility">
          <SegmentedControl
            value={visibility}
            onChange={setVisibility}
            options={[
              { value: 'private', label: 'Private' },
              { value: 'unlisted', label: 'Unlisted' },
              { value: 'public', label: 'Public' },
            ]}
          />
        </SettingRow>

        <SettingRow label="Require validation before publish" hint="Block publishing if there are unresolved errors.">
          <SettingsToggle checked={requireValidation} onChange={setRequireValidation} label="Require validation" />
        </SettingRow>

        <SettingRow label="Allow search indexing" hint="Let search engines index your public scenarios.">
          <SettingsToggle checked={searchIndexing} onChange={setSearchIndexing} label="Allow search indexing" />
        </SettingRow>

        <SettingRow label="Slug style" hint="How the public URL slug is generated by default.">
          <SegmentedControl
            value={slugStyle}
            onChange={setSlugStyle}
            options={[
              { value: 'random', label: 'Random' },
              { value: 'scenario_title', label: 'Title' },
              { value: 'workspace_prefix', label: 'Prefix' },
            ]}
          />
        </SettingRow>
      </SettingsSection>

      <SaveBar saveState={saveState} onSave={handleSave} onReset={handleReset} />
    </>
  )
}
